/*
 * PVRouter configurator - ESPHome YAML for the mk2Wifi module (ESP32-C6).
 *
 * Based on the reference configuration (gist 986e1cb0fc020fa6324ccc151006af99), with the
 * sensors of what the router actually sends and one control per router input wired to the
 * module.
 *
 * Fail-safe: the router inputs are active LOW with a pull-up. The module only ever pulls a
 * line LOW (open drain) for the non-default state and otherwise releases it, so a broken
 * wire, an open jumper or an ESP32 that reboots or hangs at boot leaves the router in its
 * default state: routing ON, router running, no boost, no rotation. Every control goes back
 * to that state at each boot of the module.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require('./model.js'));
  else root.PVRYaml = factory(root.PVRModel);
})(typeof self !== 'undefined' ? self : this, function (M) {
  'use strict';

  // Entity names, in the language of the Home Assistant installation
  const NAMES = {
    fr: {
      controls: 'Contrôles',
      sensors: 'Capteurs',
      fallback: 'Point d’accès de secours',
      power: 'Puissance instantanée',
      powerL: (i) => `Puissance instantanée L${i}`,
      voltageL: (i) => `Tension L${i}`,
      diversion: (i) => `Taux de routage charge ${i}`,
      relayPower: 'Puissance moyenne relais',
      relay: (i) => `Relais ${i}`,
      temperature: (i) => `Température ${i}`,
      noDiversionRaw: 'Absence routage en secondes',
      noDiversion: 'Absence routage',
      offPeak: 'Heures creuses',
      sampleSets: 'Échantillons par période',
      sampleSetsPerCycle: 'Échantillons par cycle (min)',
      swDiversion: 'Routage',
      swRouterOff: 'Routeur arrêté',
      swOverride: (n, i) => (n > 1 ? `Marche forcée ${i}` : 'Marche forcée'),
      swOffPeak: 'Signal heures creuses',
      btnRotation: 'Rotation des priorités',
      restart: 'Redémarrer l’ESP',
    },
    en: {
      controls: 'Controls',
      sensors: 'Sensors',
      fallback: 'Fallback Hotspot',
      power: 'Grid power',
      powerL: (i) => `Grid power L${i}`,
      voltageL: (i) => `Voltage L${i}`,
      diversion: (i) => `Load ${i} diversion rate`,
      relayPower: 'Relay average power',
      relay: (i) => `Relay ${i}`,
      temperature: (i) => `Temperature ${i}`,
      noDiversionRaw: 'No diversion in seconds',
      noDiversion: 'No diversion',
      offPeak: 'Off-peak',
      sampleSets: 'Sample sets per period',
      sampleSetsPerCycle: 'Sample sets per cycle (min)',
      swDiversion: 'Diversion',
      swRouterOff: 'Router OFF',
      swOverride: (n, i) => (n > 1 ? `Boost ${i}` : 'Boost'),
      swOffPeak: 'Off-peak signal',
      btnRotation: 'Rotate priorities',
      restart: 'Restart ESP',
    },
  };

  const q = (s) => JSON.stringify(String(s)); // YAML double-quoted scalar
  const gpio = (pin) => `GPIO${M.MK2WIFI_GPIO[pin]}`;

  // An open-drain output: released (pull-up of the router) when inactive
  function openDrainPin(pin, activeLow) {
    return [
      '    pin:',
      `      number: ${gpio(pin)}  # D${pin}, solder jumper D${pin} closed`,
      '      mode:',
      '        output: true',
      '        open_drain: true',
      ...(activeLow ? ['      inverted: true'] : []),
    ];
  }

  function sensor(tag, name, id, extra) {
    return [
      '  - platform: mk2pvrouter',
      `    tag_name: ${q(tag)}`,
      `    name: ${q(name)}`,
      ...(id ? [`    id: ${id}`] : []),
      ...extra.map((l) => `    ${l}`),
      '',
    ];
  }

  const WATT = ['unit_of_measurement: W', 'device_class: power', 'state_class: measurement', 'accuracy_decimals: 0'];
  const sorted = (group) => ['web_server:', `  sorting_group_id: ${group}`];

  function yaml(m) {
    const t = NAMES[m.mk2wifi.language] || NAMES.fr;
    const name = m.mk2wifi.name || 'mk2pvrouter';
    const friendly = m.mk2wifi.friendlyName || 'Mk2PVRouter';
    const iot = m.serialOutput === 'IoT';
    const espTemp = m.temperature.mode === 'esp';
    const inputs = M.wifiInputs(m);
    const jumpers = inputs.map((c) => `D${c.pin}`).sort();
    const L = [];
    const add = (...xs) => L.push(...xs);

    add(
      '# Generated by the PVRouter configurator: https://fredm67.github.io/Mk2PVRouter/configurateur/',
      '# For the mk2Wifi module, with the matching router config.h generated at the same time.',
      '#',
      `# Solder jumpers to close on the module: ${jumpers.length ? jumpers.join(', ') : 'none'}`,
      `# TEMP jumper of the motherboard: ${espTemp ? '3-centre (the ESP32-C6 reads the DS18B20 probes)' : 'other position (3-centre gives the probes to the ESP32-C6)'}`,
      '#',
      '# Fail-safe: the module only pulls a router input LOW for the non-default state, and',
      '# releases it otherwise. A broken wire or a module that reboots leaves the router in its',
      '# default state (routing ON, no boost); every control returns to it at each boot.',
      '',
      'esphome:',
      `  name: ${q(name)}`,
      `  friendly_name: ${q(friendly)}`,
      '  on_boot:',
      '    priority: -100  # Lower priority to ensure it runs after other boot tasks',
      '    then:',
      '      - delay: 30s  # Wait for 30 seconds after boot',
      '      - logger.set_level:',
      '          level: INFO  # Change to INFO level after delay',
      '      - logger.set_level:',
      '          tag: component',
      '          level: ERROR',
      '      - lambda: |-',
      '          id(boot_done) = true;',
      '',
      'esp32:',
      '  board: esp32-c6-devkitc-1  # module mk2Wifi (ESP32-C6-MINI-1)',
      '  framework:',
      '    type: esp-idf',
      '',
      'external_components:',
      '  - source:',
      '      type: git',
      '      url: https://github.com/FredM67/esphome_components',
      '    components: [ mk2pvrouter ]',
      '    refresh: 1d',
      '',
      'logger:',
      '  baud_rate: 0  # the UART talks to the router',
      '  level: DEBUG',
      '',
      'api:',
      '  encryption:',
      '    key: !secret api_encryption_key',
      '',
      'ota:',
      '  - platform: esphome',
      '    password: !secret esphome_ota_password',
      '',
      'wifi:',
      '  ssid: !secret wifi_ssid',
      '  password: !secret wifi_password',
      '  ap:',
      `    ssid: ${q(`${friendly} ${t.fallback}`.slice(0, 32))}`,
      '    password: !secret wifi_fallback_password',
      '',
      'captive_portal:',
      '',
      'web_server:',
      '  version: 3',
      '  local: true',
      '  port: 80',
      '  auth:',
      '    username: !secret esphome_web_server_username',
      '    password: !secret esphome_web_server_password',
      '  sorting_groups:',
      '    - id: sorting_group_controls',
      `      name: ${q(t.controls)}`,
      '      sorting_weight: -10',
      '    - id: sorting_group_sensors',
      `      name: ${q(t.sensors)}`,
      '      sorting_weight: -5',
      '',
      'globals:',
      '  - id: boot_done',
      '    type: bool',
      '    restore_value: false',
      "    initial_value: 'false'",
      ''
    );

    if (espTemp)
      add('one_wire:', '  - platform: gpio', `    pin: GPIO${M.MK2WIFI_ONEWIRE_GPIO}  # TEMP jumper on 3-centre`, '');

    if (iot)
      add(
        'uart:',
        `  tx_pin: GPIO${M.MK2WIFI_UART.tx}  # -> RX of the router`,
        `  rx_pin: GPIO${M.MK2WIFI_UART.rx}  # <- TX of the router`,
        '  baud_rate: 9600',
        '  parity: EVEN',
        '  data_bits: 7',
        '  stop_bits: 1',
        '',
        'mk2pvrouter:',
        `  update_interval: ${m.datalogPeriod}s`,
        ''
      );

    add('i2c:', '  - id: bus_oled', '    sda: GPIO6  # OLED connector of the module', '    scl: GPIO7', '    scan: true', '');

    // ---- sensors ----
    add('sensor:');
    if (iot) {
      add(...sensor('P', t.power, 'p_grid', [...WATT, ...sorted('sorting_group_sensors')]));
      for (let i = 1; i <= 3; ++i) add(...sensor(`P${i}`, t.powerL(i), `p${i}_grid`, [...WATT, ...sorted('sorting_group_sensors')]));
      for (let i = 1; i <= 3; ++i)
        add(...sensor(`V${i}`, t.voltageL(i), `v${i}_grid`, ['unit_of_measurement: V', 'device_class: voltage', 'state_class: measurement', 'accuracy_decimals: 1', 'filters:', '  - multiply: 0.01', ...sorted('sorting_group_sensors')]));
      m.loads.forEach((_, i) =>
        add(...sensor(`D${i + 1}`, t.diversion(i + 1), `d${i + 1}_rate`, ['unit_of_measurement: "%"', 'state_class: measurement', 'accuracy_decimals: 0', 'icon: "mdi:water-boiler"', ...sorted('sorting_group_sensors')]))
      );
      if (m.relays.enabled) add(...sensor('R', t.relayPower, 'p_relay', [...WATT, ...sorted('sorting_group_sensors')]));
      if (M.tempSensorPresent(m))
        m.temperature.sensors.forEach((s, i) =>
          add(...sensor(`T${i + 1}`, s.name || t.temperature(i + 1), `t${i + 1}`, ['unit_of_measurement: "°C"', 'device_class: temperature', 'state_class: measurement', 'accuracy_decimals: 1', 'filters:', '  - multiply: 0.01', ...sorted('sorting_group_sensors')]))
        );
      add(...sensor('N', t.noDiversionRaw, 'no_ed_raw', ['unit_of_measurement: s', 'internal: true']));
      add(...sensor('S', t.sampleSets, null, ['unit_of_measurement: ""', 'accuracy_decimals: 0', 'icon: "mdi:counter"', 'entity_category: diagnostic']));
      add(...sensor('S_MC', t.sampleSetsPerCycle, null, ['unit_of_measurement: ""', 'accuracy_decimals: 0', 'icon: "mdi:counter"', 'entity_category: diagnostic']));
    }
    if (espTemp)
      m.temperature.sensors.forEach((s, i) => {
        const a = M.parseAddress(s.address);
        add(
          '  - platform: dallas_temp',
          ...(a ? [`    address: 0x${a.map((b) => b.toString(16).toUpperCase().padStart(2, '0')).join('')}`] : []),
          `    name: ${q(s.name || t.temperature(i + 1))}`,
          `    id: t${i + 1}`,
          '    update_interval: 30s',
          '    web_server:',
          '      sorting_group_id: sorting_group_sensors',
          ''
        );
      });
    add(
      '  - platform: wifi_signal',
      '    name: "WiFi Signal"',
      '    unit_of_measurement: dB',
      '    device_class: signal_strength',
      '    accuracy_decimals: 0',
      '    update_interval: 60s',
      '',
      '  - platform: uptime',
      '    name: "Uptime"',
      '    unit_of_measurement: s',
      '    device_class: duration',
      '    icon: "mdi:timer-outline"',
      '    accuracy_decimals: 0',
      '    update_interval: 60s',
      ''
    );

    // ---- binary sensors ----
    const binaries = [];
    if (iot && m.relays.enabled) m.relays.list.forEach((_, i) => binaries.push([`R${i + 1}`, t.relay(i + 1), 'power']));
    if (iot && m.dualTariff.enabled) binaries.push(['TA', t.offPeak, null]);
    if (binaries.length) {
      add('binary_sensor:');
      for (const [tag, label, cls] of binaries)
        add('  - platform: mk2pvrouter', `    tag_name: ${q(tag)}`, `    name: ${q(label)}`, ...(cls ? [`    device_class: ${cls}`] : []), '    web_server:', '      sorting_group_id: sorting_group_sensors', '');
    }

    // ---- text sensors ----
    add('text_sensor:');
    if (iot)
      add(
        '  - platform: template',
        `    name: ${q(t.noDiversion)}`,
        '    id: no_ed',
        '    icon: "mdi:timelapse"',
        `    update_interval: ${m.datalogPeriod}s`,
        '    lambda: |-',
        '      int total_seconds = id(no_ed_raw).state;',
        '      int hours = total_seconds / 3600;',
        '      int minutes = (total_seconds % 3600) / 60;',
        '      int seconds = total_seconds % 60;',
        '      char buffer[24];',
        '      snprintf(buffer, sizeof(buffer), "%02d h %02d min %02d s", hours, minutes, seconds);',
        '      return {buffer};',
        '    web_server:',
        '      sorting_weight: 20',
        '      sorting_group_id: sorting_group_sensors',
        ''
      );
    add(
      '  - platform: wifi_info',
      '    ip_address:',
      '      name: IP Address',
      '      icon: "mdi:lan"',
      '    mac_address:',
      '      name: Wifi Mac Address',
      '      icon: "mdi:identifier"',
      '    ssid:',
      '      name: Wifi SSID',
      '      icon: "mdi:wifi-check"',
      '    bssid:',
      '      name: Wifi BSSID',
      '      icon: "mdi:wifi-check"',
      ''
    );

    // ---- controls ----
    add('switch:');
    const overrides = inputs.filter((c) => c.kind === 'override');
    let rotation = null;
    for (const c of inputs) {
      if (c.kind === 'diversion')
        // ON = line released = routing, the default
        add('  - platform: gpio', ...openDrainPin(c.pin, false), `    name: ${q(t.swDiversion)}`, '    id: sw_diversion', '    restore_mode: ALWAYS_ON', '    icon: "mdi:solar-power"', ...sorted('sorting_group_controls').map((l) => `    ${l}`), '');
      else if (c.kind === 'routerOff')
        add('  - platform: gpio', ...openDrainPin(c.pin, true), `    name: ${q(t.swRouterOff)}`, '    id: sw_router_off', '    restore_mode: ALWAYS_OFF', '    icon: "mdi:power"', ...sorted('sorting_group_controls').map((l) => `    ${l}`), '');
      else if (c.kind === 'override') {
        const i = overrides.indexOf(c) + 1;
        add('  - platform: gpio', ...openDrainPin(c.pin, true), `    name: ${q(t.swOverride(overrides.length, i))}`, `    id: sw_boost_${i}`, '    restore_mode: ALWAYS_OFF', '    icon: "mdi:fire"', ...sorted('sorting_group_controls').map((l) => `    ${l}`), '');
      } else if (c.kind === 'dualTariff')
        add('  - platform: gpio', ...openDrainPin(c.pin, true), `    name: ${q(t.swOffPeak)}`, '    id: sw_off_peak', '    restore_mode: ALWAYS_OFF', '    icon: "mdi:clock-outline"', ...sorted('sorting_group_controls').map((l) => `    ${l}`), '');
      else if (c.kind === 'rotation') {
        // the router rotates on a falling edge: a pulse, driven by the button below
        rotation = c;
        add('  - platform: gpio', ...openDrainPin(c.pin, true), '    id: sw_rotation', '    internal: true', '    restore_mode: ALWAYS_OFF', '');
      }
    }
    add(
      '  - platform: template',
      '    name: "Debug Mode"',
      '    optimistic: true',
      '    id: api_debug_switch',
      '    restore_mode: RESTORE_DEFAULT_OFF',
      '    entity_category: diagnostic',
      '    on_turn_on:',
      '      - logger.set_level:',
      '          level: DEBUG',
      '    on_turn_off:',
      '      - if:',
      '          condition:',
      '            lambda: |-',
      '              return id(boot_done);',
      '          then:',
      '            - logger.set_level:',
      '                level: INFO',
      '',
      'button:'
    );
    if (rotation)
      add(
        '  - platform: template',
        `    name: ${q(t.btnRotation)}`,
        '    icon: "mdi:rotate-right"',
        '    on_press:',
        '      - switch.turn_on: sw_rotation',
        '      - delay: 2s  # the router reads its inputs once per second',
        '      - switch.turn_off: sw_rotation',
        '    web_server:',
        '      sorting_group_id: sorting_group_controls',
        ''
      );
    add('  - platform: restart', `    name: ${q(t.restart)}`);
    return L.join('\n') + '\n';
  }

  return { yaml, NAMES };
});
