permissions:
  contents: read
name: Code Formatting Check

on:
  pull_request:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - ".clang-format"
      - "formatter.sh"
      - "Mk2_3phase_RFdatalog_temp/**"
  push:
    paths:
      - ".github/workflows/code-formatting-check.yml"
      - ".clang-format"
      - "formatter.sh"
      - "Mk2_3phase_RFdatalog_temp/**"

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '18'
        check-path: 'Mk2_3phase_RFdatalog_temp'
        fallback-style: 'Mozilla' # optional
