name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{ github.actor }} , thank you for submitting an issue!'
        pr_message: 'Hello @${{ github.actor }} , thank you submitting a pull request!'
